### ISSUE TITLE
Syntax error for random_user_agents

### ISSUE THREAD

**Issue by NFTsibeiho** [sj-dan/OpenSea-NFT-Stealer#21]
**Describe the bug**
I know this might sound very straightforward to many, but for a noob like me it gave me quite a nightmare for a while.
import random_user_agents gives me a syntax error.
I finally realised I had to use import random_user_agent

**The collection you were trying to download**
Its downloading really great now!

**Expected behavior**

**Terminal output (please show the error that the console showed)**
```
paste here
```

**Comment by sj-dan** [comment]
@NFTsibeiho First of all, this isn't a bug. The script never contained the line `import random_user_agents`. It has always been `import random_user_agent`. The only way you'd be getting such an error is if you modified the script.

Secondly, how are you getting a syntax error, when the issue was a module that doesn't exist?

Lastly, why create a bug report when your issue was resolved?

This is not a valid bug report.

**Comment by NFTsibeiho** [comment]
lol. Sorry im really noob in this python thing. Anyways the import random_user_agents is from your README.md

**Comment by NFTsibeiho** [comment]
Btw the script is working really well! Thanks so much for sharing this!

**Comment by sj-dan** [comment]
> lol. Sorry im really noob in this python thing. Anyways the import random_user_agents is from your README.md

It's alright. The README.md doesn't say to use `import random_user_agents`, it says to install the pip package, using `pip install random_user_agents`. In the future, just remember, if you already solved your issue, don't create a bug report.

**Comment by NFTsibeiho** [comment]
ok got it. Thanks!

**Comment by NFTsibeiho** [comment]
![Annotation 2022-01-23 101812](https://user-images.githubusercontent.com/98242248/150662056-8c09c9e7-01e7-4742-bf52-9d44f61356e8.png)

Sorry Im not exactly sure where to ask about this, I cant seem to extract all the pictures for cryptopunks, is there anything I can rectify for that?
